ALTER TYPE "CrmFieldType" ADD VALUE IF NOT EXISTS 'LONG_TEXT';
ALTER TYPE "CrmFieldType" ADD VALUE IF NOT EXISTS 'URL';
ALTER TYPE "CrmFieldType" ADD VALUE IF NOT EXISTS 'EMAIL';
ALTER TYPE "CrmFieldType" ADD VALUE IF NOT EXISTS 'PHONE';
ALTER TYPE "CrmFieldType" ADD VALUE IF NOT EXISTS 'USER';

ALTER TABLE "CrmField"
ADD COLUMN "visible" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "section" TEXT,
ADD COLUMN "helpText" TEXT;

ALTER TABLE "Invoice"
ADD COLUMN "notes" TEXT,
ADD COLUMN "terms" TEXT,
ADD COLUMN "lineItems" JSONB,
ADD COLUMN "customFields" JSONB,
ADD COLUMN "relatedLinks" JSONB,
ADD COLUMN "relatedRecords" JSONB;

ALTER TABLE "Project"
ADD COLUMN "ownerName" TEXT,
ADD COLUMN "siteName" TEXT,
ADD COLUMN "location" TEXT,
ADD COLUMN "linkedRecords" JSONB,
ADD COLUMN "proofLinks" JSONB,
ADD COLUMN "externalLinks" JSONB,
ADD COLUMN "customFields" JSONB;

ALTER TABLE "ProjectTask"
ADD COLUMN "proofLinks" JSONB;
